[project]
name = "dissertacao-csr-analyzer"

[services.web]
name = "web"
start = "uvicorn csr_analyzer.web_app:app --host 0.0.0.0 --port 8000"
restartPolicyType = "ON_FAILURE"

[deploy]
healthcheckPath = "/"
numReplicas = 1
restartPolicyType = "ON_FAILURE"

